<a href="https://colab.research.google.com/github/Hirokazzz/DataScientistLab/blob/master/%E3%83%A9%E3%83%B3%E3%83%80%E3%83%A0%E3%83%95%E3%82%A9%E3%83%AC%E3%82%B9%E3%83%88%26%E8%A4%87%E6%95%B0%E3%83%A2%E3%83%86%E3%82%99%E3%83%AB%E3%81%A7Iris%E5%88%86%E6%9E%90%E3%81%99%E3%82%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

参考文献：東京大学のデータサイエンティスト育成講座

### アイリスのクラス分類 ランダムフォレスト＆複数モデル


In [ ]:
# ライブラリの読み込み
import numpy as np
from scipy import sparse
import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import display
import sys
from sklearn.datasets import make_classification

In [ ]:
#scikitlearnからIrisデータを読み込む
from sklearn.datasets import load_iris
iris_dataset = load_iris()

In [ ]:
print("5件だけデータ表示: \n{}".format(iris_dataset['data'][:5]))

5件だけデータ表示: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [ ]:
#データサイズの確認
print("Shape of data: {}".format(iris_dataset['data'].shape))

Shape of data: (150, 4)


### 訓練データとテストデータの分離


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
  iris_dataset['data'],iris_dataset['target'],random_state=0
)

In [ ]:
#クラスタリング各モデルの読み込み
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

### モデルをテストして精度を確認する

In [ ]:
model_list = {'非線形SVM':SVC(gamma="scale"),
              '決定木':DecisionTreeClassifier(random_state=0),
              'ランダムフォレスト':RandomForestClassifier(100),
              'k-近傍法':KNeighborsClassifier(n_neighbors=1)}

for model_name,model in model_list.items():
  model.fit(X_train,y_train)
  print(model_name)
  print('正解率:'+str(model.score(X_train,y_train)))
  print('正解率2:'+str(model.score(X_test,y_test)))
  

非線形SVM
正解率:0.9642857142857143
正解率2:0.9736842105263158
決定木
正解率:1.0
正解率2:0.9736842105263158
ランダムフォレスト
正解率:1.0
正解率2:0.9736842105263158
k-近傍法
正解率:1.0
正解率2:0.9736842105263158
